### YamlMime:ModuleUnit
uid: learn.introduction-to-git.02-install-and-configure
title: Install and Configure Git
metadata:
  title: Install and Configure Git
  description: TODO
  ms-date: 05/06/2019
  author: ssavitzky
  ms-author: TBD
  ms.topic: interactive-tutorial
  ms.prod: learning-git
  ROBOTS: NOINDEX
durationInMinutes: 9
content: |
  [!include[](includes/02-install-and-configure.md)]
