### YamlMime:ModuleUnit
uid: learn.introduction-to-git.02-install-and-configure
title: Install and Configure Git
metadata:
  title: Install and Configure Git
  description: TODO
  ms-date: 03/27/2019
  author: ssavitzky
  ms-author: TODO
  ms.topic: interactive-tutorial
  ms.prod: learning-git
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/02-install-and-configure.md)]
