### YamlMime:ModuleUnit
uid: learn.introduction-to-git.1-install-and-configure
title: Install and configure Git
metadata:
  title: Install and configure Git
  description: Install Git and configure it with your name and email
  ms.date: 06/24/2019
  author: v-jeffpr
  ms.author: shana.matthews
  ms.topic: interactive-tutorial
  ms.prod: learning-git
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/1-install-and-configure.md)]
